apiVersion: apps/v1 
kind: ReplicaSet 
metadata:
  name: trans-app-rs 
spec:
  relicas: 4
  selector:
    matchLabels:
      app: trans
  template:
    metadata:
      labels:
        app: trans 
      spec: 
        containers:
          - name: app-web
            image: muralisocial123/aws-trans-image:latest
            ports:
              - containerPort: 4545



